// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diyfbqglbrxwcsrhosqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeWZicWdsYnJ4d2Nzcmhvc3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDY2NzYsImV4cCI6MjA3Mzg4MjY3Nn0.b8cSycXNeUXkUKB7CAJ-7nZ-zgevz45UGoDHh6u5UaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});